version: '3.8'
services:
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ecommerce      
    ports:
      - "5432:5432"
    volumes:
      - .data/db:/var/lib/postgresql/data  


